
#GET http://localhost:5000/api/Activities


GET http://localhost:5000/api/Activities/19e8148f-c15c-4979-b34d-2410bd35303b
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDg4MTc1MjIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJib2IiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjVjZTcwMTg3LThhOTgtNDhkYi1iMmJiLTUyNzYxMDQzZThlYyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImJvYkB0ZXN0LmNvbSIsImlhdCI6MTcwODIxMjcyMiwibmJmIjoxNzA4MjEyNzIyfQ.JhAmG3MIsWpiMVB9QkOjeiiSI5t13JLNlkYf9Tc5HVWhaLWUEVwU0daOJOP0WzuuJ4rNg5BlsVjQRX2KkFSsoA
